PR for HW3
vorobyov27/TMS_HW pull request #1
Opened 2022-10-09 22:05 UTC by vorobyov27

- add gitignore file;
 - add package.json / package-lock.json files;
 - add 3 files with advanced exercises.
 - and 3 scrypts in package.json to launch files.

2022-10-12 08:28 UTC, oromis1508 commented on advExercise1.js
> +console.log("b = "+ b +": type of b = "+typeof b);
Вариант норм, но на тот момент slice еще не изучали. Исправлять не нужно, но, как вариант:
1. a = a + b
b = a - b
a = a - b
2. a = a * b
b = a / b
a = a / b

2022-10-12 08:37 UTC, oromis1508 commented on advExercise3.ts
> +    str = str+'#'
1. Можно проще, через составное присваивание, str += '#'
2. Строки, числа, которые в теории, могут поменяться, лучше выносить в константы. Обычно константы с данными пишутся отдельно, чтобы, при необходимости их поменять, не нужно было искать их в коде. В данном случае код небольшой, но если он будет на 100-200 строк, то может быть проблематично искать эти данные.

2022-10-12 08:42 UTC, oromis1508 requested changes
В целом хорошо сделано, небольшие исправления в 3 задании. 1 выполнил с тем, что на тот момент не изучали, просто глянь другие варианты

2022-10-12 20:16 UTC, vorobyov27 commented on advExercise3.ts
> +    str = str+'#'
@oromis1508 готово, подправил упражнение№3.

2022-10-13 14:12 UTC, oromis1508 approved these changes

2022-10-15 15:10 UTC, merged