add HW12, ex1,ex2
vorobyov27/TMS_HW pull request #10
Opened 2022-11-16 17:20 UTC by vorobyov27

2022-11-20 19:31 UTC, oromis1508 commented on HW12/mainCar.ts
> +    abstract fuelType: string;
Поля, которые не используются вне класса, нужно определять как private/protected, которые не редактируюся - readonly.

2022-11-20 19:35 UTC, oromis1508 commented on HW12/mainCar.ts
> +enum FuelCost {
Обычно в 1 файле находится 1 сущность (класс, интерфейс/енам). Исключение - когда они тесно связаны (вроде class Car, enum TransmissionType или класс FilterForm, enum FilterFields)

2022-11-20 19:37 UTC, oromis1508 commented on HW12/mainCar.ts
> +    }
Не учтено, что нельзя заправиться больше объема бака, как вариант, можно что-то в этом роде:

    protected drive (distance: number) : void {
        const fuelForDistance = (this.fuelConsuption*distance)/100;
        while(fuelForDistance > this.fuelReserve) {
            const distancePassed = this.fuelReserve / this.fuelConsuption * 100;
            this.fuelReserve = 0;
            this.refuel();//можно с параметром
            this.drive(distance - distancePassed);
        }
        this.fuelReserve -= fuelForDistance;
    }

2022-11-20 19:39 UTC, oromis1508 commented on HW12/mainCar.ts
> +            this.fuelReserve = fuelAmount;
не учтено, что this.fuelReserve уже может быть не 0

2022-11-20 19:40 UTC, oromis1508 commented on HW12/mainCar.ts
> +            console.log(`Added maximum fuel! Fuel bill = ${FuelCost[this.fuelType]*this.maxFuel}`);
Это нужно было не вывести в консоль, а использовать Bills.addBill

2022-11-20 19:43 UTC, oromis1508 commented on HW12/bills.ts
> +    private static billSum: number;
это будет или объект типа { [key: string]: number } или Map<string, number> или массив [string, number][]

2022-11-20 19:45 UTC, oromis1508 requested changes
2 не до конца сделано, Bills нужно было использовать в refuel, плюс есть немного комментов по улучшению кода

2022-11-21 19:49 UTC, vorobyov27 commented on HW12/mainCar.ts
> +    }
Проверка на объём бака у меня встроена в метод refuel()

 else if ((fuelAmount == null) || (fuelAmount > this.maxFuel)) {
            this.fuelReserve = this.maxFuel;
            console.log(`Added maximum fuel! Fuel bill = ${FuelCost[this.fuelType]*this.maxFuel}`);

т.е. если мы в refuel не указываем входной параметр, либо указываем кол-во литров большее, чем объём бака, то заправляем просто полный бак.

2022-11-21 21:23 UTC, vorobyov27 commented on HW12/mainCar.ts
> +            console.log(`Added maximum fuel! Fuel bill = ${FuelCost[this.fuelType]*this.maxFuel}`);
не до конца понял задание) поправил.

2022-11-21 21:31 UTC, vorobyov27 commented
Добавил исправления, с учётом замечаний:
1) Поправил замечания по коду: сделал поля protected и убрал ненужный enum из mainCar.ts - сейчас мы его импортируем из класса Bills.
2) Поправил метод refuel(). Добавил заправку бака с учётом оставшегося топлива.
3) Поправил класс Bills: дописал методы getBill / addBill, согласно описанию.
4) В refuel() добавил вызов метода addBill при каждой заправке. Добавил вызов итогового getBill после завершения поездки.

2022-11-23 18:01 UTC, oromis1508 commented on HW12/mainCar.ts
> +            const fuelIndexFullTank = Math.abs(Math.ceil(calcFuel / this.maxFuel));
Нужен Math.floor, ceil возвращает большее значение, т.е. при результате 2.25 будет 3 и fuelIndexPartial получится 2,25 - 3

2022-11-23 18:02 UTC, oromis1508 approved these changes
Всё нормально исправил, только в drive не то округление выбрал

2022-12-04 18:05 UTC, merged