Hw17
vorobyov27/TMS_HW pull request #13
Opened 2022-12-06 22:36 UTC by vorobyov27

Tasks 1,2,3.

2022-12-14 09:46 UTC, oromis1508 requested changes
По html всё ок. По тестам, вообще нет негативных кейсов. 0 * 0 === 1 это не негативный кейс, а ошибка в написании теста. Негативные тесты принимают нестандартные входные данные, и ожидаемый результат, как функция должна обрабатывать такие данные. Т.е. например testAdd(NaN, 0, NaN). Возможные кейсы я покажу в рамках следующего занятия

2022-12-14 20:06 UTC, vorobyov27 commented
> По html всё ок. По тестам, вообще нет негативных кейсов. 0 * 0 === 1 это не негативный кейс, а ошибка в написании теста. Негативные тесты принимают нестандартные входные данные, и ожидаемый результат, как функция должна обрабатывать такие данные. Т.е. например testAdd(NaN, 0, NaN). Возможные кейсы я покажу в рамках следующего занятия

Ох, тут я что-то затупил. 
Поправил: добавил негативные кейсы, добавил в функциях обработку входных данных NaN, обработку деления на 0.

2022-12-15 09:03 UTC, oromis1508 commented on HW17/test.ts
> +    else if (isNaN(arg1)||isNaN(arg2)) {
только это нужно обрабатывать в самой функции, т.к. все равно в функции есть возможность получения аргументов NaN и в зависимости от реализации, она всё равно что-то должна сделать с ними

2022-12-15 09:04 UTC, oromis1508 requested changes
Добавил коммент по поводу NaN

2022-12-18 17:45 UTC, vorobyov27 commented on HW17/test.ts
> +    else if (isNaN(arg1)||isNaN(arg2)) {
> только это нужно обрабатывать в самой функции, т.к. все равно в функции есть возможность получения аргументов NaN и в зависимости от реализации, она всё равно что-то должна сделать с ними

перенёс проверки на входные значения, поправил тесты.

2022-12-18 23:52 UTC, oromis1508 approved these changes
Теперь ок

2022-12-19 20:43 UTC, merged