Hw18
vorobyov27/TMS_HW pull request #14
Opened 2022-12-11 19:26 UTC by vorobyov27

- add main file with class and methods; 
- add chai / mocha tests;
- add jest tests;
- add config files.

2022-12-15 10:25 UTC, oromis1508 commented on HW18/TestStrings.ts
> +                }
Условие можно перенести в сам while:

    let targetPosition = 0;
    while(targetPosition !== -1) {
    targetPosition = mainStr.indexOf(subStr, position);
    ...

2022-12-15 10:31 UTC, oromis1508 commented on HW18/TestStrings.ts
> +            while (true) {
здесь лучше цикл for, т.к. есть инициализация counter и counter++; после каждого витка

2022-12-15 10:38 UTC, oromis1508 commented on HW18/TestStrings.ts
> +        } else {
здесь еще можно добавить проверку, что количество подстрок не меньше, чем индекс

2022-12-15 10:39 UTC, oromis1508 commented on HW18/TestStrings.ts
> +        if (firstArr.length < 1 || secondArr.length < 1) {
еще может быть 2 проверки: что массивы равны по длине и что ни один из элементов массива не выходит за рамки длины строки

2022-12-15 10:40 UTC, oromis1508 requested changes
Есть несколько комментов, по самим тестам, нормально, но можно еще добавить условия, которые я указал и их проверку

2022-12-18 19:31 UTC, vorobyov27 commented
Добавил доработки по замечаниям 3 и 4.
По замечаниям 1 и 2:  если перенести условие targetPos !== -1 выше  (в while), то возникает проблема: т.к. targetPos вычисляется внутри цикла while, то если окажется, что targetPos == -1, оставшиеся действия внутри цикла всё-равно выполнятся - т.е. всё-равно нужно будет добавлять проверку и break - как сделано сейчас.

2022-12-19 00:00 UTC, oromis1508 commented on HW18/TestStrings.ts
> +            totalArr.forEach(el => {
Здесь вместо forEach можно использовать totalArr.any, он как раз для таких случаев и нужен

2022-12-19 00:08 UTC, oromis1508 commented on HW18/TestStrings.ts
> +                }
Тогда так (во втором случае также, присвоение можно сделать не 0, а первого индекса):

            let position = mainStr.indexOf(subStr);
            while(targetPosition !== -1) {
            totalArray.push(targetPosition);
            position = mainStr.indexOf(subStr, position + 1);
            }

2022-12-19 00:09 UTC, oromis1508 approved these changes

2022-12-19 21:50 UTC, vorobyov27 commented on HW18/TestStrings.ts
> +                }
> Тогда так (во втором случае также, присвоение можно сделать не 0, а первого индекса):

Поправил оба метода согласно комментарию - вынес проверку на -1 в условие цикла, поменял присвоение - сделал с первого индекса.

2022-12-19 21:52 UTC, merged