add HW19
vorobyov27/TMS_HW pull request #15
Opened 2022-12-14 19:39 UTC by vorobyov27

- added jestTests;
 - added test-data with test user creds.

2022-12-19 00:31 UTC, oromis1508 requested changes
При тестировании API обычно на 1 запрос пишется 1 тест, поэтому недостаточно проверять только код, обычно проверяются важдые для запроса поля, например при создании юзера, что есть айди в ответе и совпадают отправленные поля

2022-12-19 22:26 UTC, vorobyov27 commented
> поля
Добавил недостающие проверки полей в тесты, где проверялся только код ответа.

2022-12-21 10:43 UTC, oromis1508 requested changes
По проверкам норм. Еще вчера я озвучивал, что в 1 файле 1 сьюта и сьюты лучше не группировать positive-negative (здесь норм, т.к. мало тестов, но когда их много, то сложновато найти нужный). Лучше группировать по функционалу, вроде 'users api', 'register api', 'login api'...

2022-12-28 18:52 UTC, vorobyov27 commented
> По проверкам норм. Еще вчера я озвучивал, что в 1 файле 1 сьюта и сьюты лучше не группировать positive-negative (здесь норм, т.к. мало тестов, но когда их много, то сложновато найти нужный). Лучше группировать по функционалу, вроде 'users api', 'register api', 'login api'...

Поправил организацию тестов: разделил тесты по принципу "1 файл - 1 сьют": в каждом сьюте собрал тесты, связанные по функционалу: тесты по логину, регистрации, работе с юзером, работе с ресурсами.

2022-12-30 11:33 UTC, oromis1508 approved these changes
Вопросов больше нет, всё отлично

2023-01-03 20:59 UTC, merged