add HW20: 1,2
vorobyov27/TMS_HW pull request #16
Opened 2022-12-18 21:30 UTC by vorobyov27

2022-12-30 12:12 UTC, oromis1508 commented on HW20/steamTest.ts
> +        console.log("Price: "+await driver.findElement(By.xpath(`//div[@id="tab_newreleases_content"]//a[contains(@href, "app")][${i}]//*[@class="discount_final_price"]`)).getText())
itemAmount - не совсем корректное название элемента, т.к. это элементы
+ можно сделать таким образом, не дублируя уже найденные элементы:

        const items = await driver.findElements(By.xpath('//div[@id="tab_newreleases_content"]//a[contains(@href, "app")]'))
        for (let i = 0; i < items.length; i++) {
            console.log(`${i}.Name: `+await items[i].findElement(By.xpath(`//*[@class="tab_item_name"]`)).getText())
            console.log("Genres: "+await items[i].findElement(By.xpath(`//*[@class="tab_item_top_tags"]`)).getText())
            console.log("Price: "+await items[i].findElement(By.xpath(`//*[@class="discount_final_price"]`)).getText())
        }

2022-12-30 12:21 UTC, oromis1508 commented on HW20/tests.ts
> +    console.log(await driver.findElement(By.xpath('//table[@id="table1"]//tr[4]/td[6]/a[2]')).getAttribute('href'))
Одиночные слеши лучше вообще не использовать, если нет сильной необходимости. В рамках таблицы, одна строка будет всегда содержать столбцы для этой строки, но иногда бывает, что сами ячейки могут быть обёрнуты, например в div, для каких-нибудь стилей. Также и индексы лучше не использовать, если есть атрибуты, за которые можно зацепиться (в данном случае и для ссылок есть текст и href и для ячеек td есть классы)

2022-12-30 12:21 UTC, oromis1508 requested changes
Есть пара моментов, где можно улучшить

2023-01-03 21:50 UTC, vorobyov27 commented on HW20/tests.ts
> +    console.log(await driver.findElement(By.xpath('//table[@id="table1"]//tr[4]/td[6]/a[2]')).getAttribute('href'))
> Есть пара моментов, где можно улучшить

Поправил замечания: 
 - оптимизировал вывод списка игр: убрал дублирование и поменял название переменной
 - поправил локаторы: убрал привязку к порядковым номерам, добавил привязку к названию класса и тексту ссылки.

2023-01-04 10:37 UTC, alexch0110 approved these changes
Всё ок, исправлено что указывал

2023-01-04 19:37 UTC, merged