HW21
vorobyov27/TMS_HW pull request #17
Opened 2022-12-22 23:15 UTC by vorobyov27

Добавил тесты и файлы фреймворка.
Понимаю, что фреймворк пока организован совсем не оптимально)

2022-12-30 17:11 UTC, oromis1508 commented on HW21/pages/catalogPage.ts
> +        return '//*[@class="catalog-navigation__title"]'
Нет смысла делать геттеры в данном случае, readonly поля больше подходят здесь. Геттеры нужны, например, если нужно возвращать элемент, то в каждом случае элемент будет другим объектом, но код тот же. Также есть смысл возвращать сразу объекты By

2022-12-30 17:15 UTC, oromis1508 commented on HW21/tests/test.ts
> +        elements.waitForPageLoad();
этот метод скорее относится или к BasePage, от которой будут наследоваться все остальные страницы, или в крайнем случае к BrowserHelper

2022-12-30 17:16 UTC, oromis1508 commented on HW21/services/elements.ts
> +    public static waitForPageLoad(){
этот метод скорее относится или к BasePage, от которой будут наследоваться все остальные страницы, или в крайнем случае к BrowserHelper

2022-12-30 17:23 UTC, oromis1508 commented on HW21/tests/test.ts
> +        let flag = await checks.compareElementArrayHref(headerTabsArray, expectedTabs);
В данном случае хороший подход, что вынес сложную проверку, но в данном случае можно обойтись, у jest есть метод expect.toEqual для проверки объектов

2022-12-30 17:25 UTC, oromis1508 requested changes
Есть несколько замечаний, в основном про хранение селекторов, в виде строки есть смысл хранить только если на проекте используется только 1 вид селекторов

2023-01-03 22:44 UTC, vorobyov27 commented on HW21/pages/catalogPage.ts
> +        return '//*[@class="catalog-navigation__title"]'
Описанный метод хранения элементов был реализован в домашнем задании №22. В задании №21 требований к хранению элементов не было. Было требование "При написании использовать различные типы селекторов и локаторов" - для чего и было создано 2 метода получения элемента: по css / xpath. На практике же можно выбрать один способ описания локаторов и использовать его.
Чтобы поправить данное решение по аналогии с домашним заданием №22 - нужно будет его полностью переделать под page object model, который изучался позже.

2023-01-03 22:51 UTC, vorobyov27 commented on HW21/services/elements.ts
> +    public static waitForPageLoad(){
> этот метод скорее относится или к BasePage, от которой будут наследоваться все остальные страницы, или в крайнем случае к BrowserHelper
Поправил: перенёс метод к BrowserHelper

2023-01-04 10:39 UTC, oromis1508 commented on HW21/pages/catalogPage.ts
> +        return '//*[@class="catalog-navigation__title"]'
Вопросов нет, просто я ошибся с нумерацией, предполагал, что здесь уже нужен Page Object

2023-01-04 10:41 UTC, oromis1508 approved these changes
Всё ок, вопросов нет

2023-01-04 19:39 UTC, merged