add HW22
vorobyov27/TMS_HW pull request #18
Opened 2022-12-27 23:16 UTC by vorobyov27

- add 5 UI tests for onliner;
 - add pages, pageFactory mechanism;
 - add needed elements;
 - add helpers;

2023-01-07 16:29 UTC, oromis1508 commented on HW22/pageObject/pageFactory/pageFactory.ts
> +                break;
break; здесь не нужен, т.к. throw закончит выполнение функции

2023-01-07 16:29 UTC, oromis1508 commented on HW22/framework/elements/defaultElement.ts
> +        return this.element.click();
как раз click лучше делать, совмещая с this.waitForDisplayed(), т.к. позволит избежать части ошибок

2023-01-07 16:31 UTC, oromis1508 commented on HW22/framework/helpers/browser.ts
> +export class browser {
названия классов с большой буквы

2023-01-07 16:32 UTC, oromis1508 commented on HW22/pageObject/pages/defaultPage.ts
> +    }
Нет смысла дублировать на странице, только если `browser.switchToFrame()` был бы с параметром. Можно использовать browser.switchToFrame() в коде тестов

2023-01-07 16:34 UTC, oromis1508 commented on HW22/tests/pageSelect.spec.ts
> +        await mainPage.headerTabCatalog.waitForDisplayed();
Это то, что я писал выше, каждый раз перед кликом нужно явно вызывать метод ожидания. Будет лучше добавить его в сам метод click

2023-01-07 16:36 UTC, oromis1508 requested changes
Есть пара улучшений, но в целом очень хорошо сделано

2023-01-08 18:41 UTC, vorobyov27 commented
Добавил изменения с учётом замечаний:
 - Поправил названия классов.
 - В метод клик добавил ожидание элемента, на который кликаем. Убрал ненужные ожидания из тестов.
 - Убрал ненужные методы switchToFrame / switchToWindow: вместо них использовал стандартные методы Browser.switchToFrame  / Browser.switchToWindow.
 - убрал лишний break.

2023-01-11 19:50 UTC, oromis1508 approved these changes

2023-01-16 19:44 UTC, merged