Hw24
vorobyov27/TMS_HW pull request #19
Opened 2023-01-04 23:01 UTC by vorobyov27

add HW24 - cypress tests

2023-01-11 19:52 UTC, oromis1508 commented on cypress/e2e/spec.cy.ts
> +    cy.get('.x-title').should('be.visible').should('contain','KIA')
в cypress вместо второго should можно также использовать 'and'

2023-01-11 20:08 UTC, oromis1508 requested changes
По самим тестам ок, Page Object не использован, на занятии показал, как примерно это будет выглядеть в cypress. Даже в таком задании он нужен, т.к. некоторые элементы используются повторно и с PageObject можно избегать дублирования этих селекторов

2023-01-21 18:46 UTC, vorobyov27 commented
Добавил Page Object, Page Factory, переписал тесты с использованием  Page Object, Page Factory

2023-01-22 11:01 UTC, oromis1508 approved these changes

2023-01-23 18:47 UTC, merged