add homework #4 - advanced excersice
vorobyov27/TMS_HW pull request #2
Opened 2022-10-15 18:01 UTC by vorobyov27

Добавил решение по homework #4.

2022-10-16 21:53 UTC, oromis1508 commented on hw4adv1.ts
> +            if (regexp.exec(userInput) !== null) {
можно немного проще, isNaN(+userInput), тем более дальше +userInput будет использоваться и его значение можно было бы вынести в переменную

2022-10-16 21:56 UTC, oromis1508 commented on hw4adv1.ts
> +                const inputArray = userInput.split('');
Не имеет смысла создавать массив. Символ из строки можно также получить по индексу либо через charAt

2022-10-16 21:57 UTC, oromis1508 commented on hw4adv1.ts
> +}
Как можно было бы уменьшить объем кода:
>let numberOrString = readline4.question("Введите строку (от 5 до 15 символов) или число (от 5 до 15):\n");
let numericInput = +numberOrString;
let messageToAsk = "Угадайте букву:\n";
let maxIndex = numberOrString.length > 15 ? 15 : numberOrString.length;
let hiddenValue = numberOrString[Math.round(Math.random()*maxIndex)];

>if (!isNaN(numericInput)) {
messageToAsk = 'Угадайте число\n';
maxIndex = numericInput > 15 ? 15 : numericInput ;
hiddenValue = Math.round(Math.random()*(numericInput-1) +1).toString();
}

>let attempts = Math.ceil(maxIndex/3);

>console.clear();

Дальше всех этих переменных достаточно, чтобы сделать 1 цикл, общий для символа и числа

2022-10-16 22:00 UTC, oromis1508 requested changes
Выполнено хорошо, раздел с рандомом можно немного уменьшить. Исправления на твоё усмотрение, но хотя бы глянь, как можно было бы уменьшить объем

2022-10-17 20:58 UTC, vorobyov27 commented on hw4adv1.ts
> +}
Подфиксил с учётом замечаний: оптимизировал проверку пользовательского ввода, сделал один общий цикл для угадывания загаданного числа / символа.

2022-10-19 18:59 UTC, merged