Hw6
vorobyov27/TMS_HW pull request #4
Opened 2022-10-23 18:55 UTC by vorobyov27

2022-10-25 13:13 UTC, oromis1508 commented on HW6/advEx2.ts
> +    }
Не выполняется условие: должно работать при изменении количества и названий свойств объекта. 
При разных свойствах, но одинаковых значениях, будет возвращать true

2022-10-25 13:14 UTC, alexch0110 requested changes
По самому коду вопросов нет, но 2 задание выполено не совсем правильно

2022-10-26 18:33 UTC, vorobyov27 commented on HW6/advEx2.ts
> +    }
Я неправильно понял задание) умышленно сделал, чтобы сравнивало только по значениям свойств.
FIX: Добавил другую функцию: она сравнивает два объекта, при любом расхождении (в названии свойства или значении, в кол-ве свойств) возвращает false.

2022-10-26 20:19 UTC, oromis1508 approved these changes
Норм, тоже хороший вариант решения

2022-10-30 16:07 UTC, merged