HW7: add adv ex1 / adv ex2
vorobyov27/TMS_HW pull request #5
Opened 2022-10-24 19:57 UTC by vorobyov27

2022-10-27 08:57 UTC, oromis1508 commented on HW7/advEx1.ts
> +        if (leftPart[i] !== rightPart[j]) palindromFlag = false;
этот флаг в принципе не нужен, ты можешь сразу писать return false + если сразу возвращаешь, то у тебя нет дальнейшей проверки, которая уже не имеет смысла
В остальном норм, но есть чуть проще вариант, без разделения на parts:
>const mid = Math.floor(str.length/2));
 str[i] !== str[i - 1] при i < mid

2022-10-27 08:59 UTC, oromis1508 requested changes
Минимально можно улучшить, а так отлично.

2022-10-30 16:31 UTC, vorobyov27 commented on HW7/advEx1.ts
> +        if (leftPart[i] !== rightPart[j]) palindromFlag = false;
поправил: сделал более упрощённый вариант, без деления на части. Добавил выход из алгоритма в случае, если понимаем, что фраза уже не палиндром.

2022-10-30 18:47 UTC, alexch0110 approved these changes
Теперь всё отлично

2022-10-31 18:02 UTC, merged