adv ex 1,2
vorobyov27/TMS_HW pull request #6
Opened 2022-10-30 18:14 UTC by vorobyov27

2022-10-30 21:22 UTC, oromis1508 commented on HW8/advEx1.ts
> +    let filtredArr = arr.filter(el => (!vowelsArr.includes(el)));
vowelsArr можно сделать `["a","e","i","o","u"]`, а !vowelsArr.includes(el.toLowerCase())

2022-10-30 21:36 UTC, oromis1508 commented on HW8/advEx2.ts
> +}
довольно длинный вариант, для длинных строк может долго выполняться, есть пара вариантов проще:
>function isIso(str: string) {
    str = str.toLowerCase();
    return str.split('').every((el, ind) => el !== str[ind+1]);
}
function isIso2(str: string) {
    return str.length === new Set(str.toLowerCase().split('')).size;
}

2022-10-30 21:41 UTC, oromis1508 requested changes
1 в принципе норм, замечние не критичное, со вторым немного перемудрил

2022-10-31 18:25 UTC, vorobyov27 commented on HW8/advEx2.ts
> +}
Поправил свой вариант - сделал проход по массиву через обычные циклы.
Вариант с функцией isIso2 понял, а с isIso - не совсем: в нём мы ведь сравниваем элемент только со следующим? не учитывая, что одинаковые элементы могут стоять через несколько индексов.

2022-11-02 19:23 UTC, oromis1508 commented on HW8/advEx2.ts
> +}
Я видимо плоховато соображал, что-то не то написал в 1 функции, условие будет ind === str.lastIndexOf(el)

2022-11-02 19:24 UTC, oromis1508 approved these changes

2022-11-03 15:58 UTC, merged